# Server configuration
server:
  host: '127.0.0.1'
  #host: '0.0.0.0'
  port: 8000

# File paths
paths:
  upload_folder: '/tmp/upload'
  major_error_report: '/tmp/major_error_report.json'
  error_report: '/tmp/error_report.json'
  warning_report: '/tmp/warning_report.json'
  basic_report: '/tmp/basic_report.txt'
  extended_report: '/tmp/extended_report.txt'
  json_report: "backend/tests/test_data/expected_response.json"

# Allowed file types
allowed_file_types:
  - '.json'
  - '.tsv'
  - '.nii'
  - '.nii.gz'

# Validation Schemas
schemas:
  major_error_schema:
    PLDType:
      type: "StringValidator"
      allowed_values: ["multi-PLD", "single-PLD"]
      major_error: true
    ArterialSpinLabelingType:
      type: "StringValidator"
      allowed_values: ["PASL", "(P)CASL", "PCASL", "CASL"]
      major_error: true
    MRAcquisitionType:
      type: "StringValidator"
      allowed_values: ["2D", "3D"]
      major_error: true
    PulseSequenceType:
      type: "StringValidator"
      major_error: true
      aliases: ["ScanningSequence"]

  required_validator_schema:
    BackgroundSuppression:
      type: "BooleanValidator"
    M0Type:
      type: "StringValidator"
    TotalAcquiredPairs:
      type: "NumberValidator"
      min_error: 0
      enforce_integer: true
    AcquisitionVoxelSize:
      type: "NumberArrayValidator"
      size_error: 3
    LabelingDuration:
      type: "NumberOrNumberArrayValidator"
      aliases: "NumRFBlocks"
    PostLabelingDelay:
      type: "NumberOrNumberArrayValidator"
      aliases: ["InversionTime"]
    BolusCutOffFlag:
      type: "BooleanValidator"
    BolusCutOffTechnique:
      type: "StringValidator"
    BolusCutOffDelayTime:
      type: "NumberOrNumberArrayValidator"
      aliases: ["BolusDuration"]
    EchoTime:
      type: "NumberOrNumberArrayValidator"
    RepetitionTimePreparation:
      type: "NumberOrNumberArrayValidator"
      aliases: ["RepetitionTime"]
    FlipAngle:
      type: "NumberValidator"
      min_error: 0
      max_error_include: 360
    MagneticFieldStrength:
      type: "NumberValidator"
    Manufacturer:
      type: "StringValidator"
    ManufacturersModelName:
      type: "StringValidator"

  required_condition_schema:
    BackgroundSuppression: "all"
    M0Type: "all"
    TotalAcquiredPairs: "all"
    AcquisitionVoxelSize: "all"
    LabelingDuration:
      ArterialSpinLabelingType:
        ["PCASL", "CASL"]
    PostLabelingDelay:
      ArterialSpinLabelingType:
        ["PCASL", "CASL", "PASL"]
    BolusCutOffFlag:
      ArterialSpinLabelingType:
        "PASL"
    BolusCutOffTechnique:
      ArterialSpinLabelingType:
        "PASL"
    BolusCutOffDelayTime:
      ArterialSpinLabelingType:
        "PASL"
    EchoTime: "all"
    RepetitionTimePreparation: "all"
    FlipAngle: "all"
    MagneticFieldStrength: "all"
    Manufacturer: "all"
    ManufacturersModelName: "all"

  recommended_validator_schema:
    BackgroundSuppressionNumberPulses:
      type: "NumberValidator"
      min_error_include: 0
    BackgroundSuppressionPulseTime:
      type: "NumberArrayValidator"
      min_error: 0
    LabelingLocationDescription:
      type: "StringValidator"
    VascularCrushing:
      type: "BooleanValidator"
    VascularCrushingVENC:
      type: "NumberOrNumberArrayValidator"
      min_error_include: 0
    PCASLType:
      type: "StringValidator"
      allowed_values: ["balanced", "unbalanced"]
    CASLType:
      type: "StringValidator"
      allowed_values: ["single-coil", "double-coil"]
    LabelingDistance:
      type: "NumberValidator"
    LabelingPulseAverageGradient:
      type: "NumberValidator"
      min_error: 0
    LabelingPulseMaximumGradient:
      type: "NumberValidator"
      min_error: 0
    LabelingPulseAverageB1:
      type: "NumberValidator"
      min_error: 0
    LabelingPulseFlipAngle:
      type: "NumberValidator"
      min_error: 0
      max_error_include: 360
    LabelingPulseInterval:
      type: "NumberValidator"
      min_error: 0
    LabelingPulseDuration:
      type: "NumberValidator"
      min_error: 0
    PASLType:
      type: "StringValidator"
    LabelingSlabThickness:
      type: "NumberValidator"
      min_error_include: 0
    AcquisitionDuration:
      type: "NumberValidator"

  recommended_condition_schema:
    BackgroundSuppressionNumberPulses:
      BackgroundSuppression:
        True
    BackgroundSuppressionPulseTime:
      BackgroundSuppression:
        True
    LabelingLocationDescription: "all"
    VascularCrushing: "all"
    VascularCrushingVENC:
      VascularCrushing:
        True
    PCASLType:
      ArterialSpinLabelingType:
        "PCASL"
    CASLType:
      ArterialSpinLabelingType:
        "CASL"
    LabelingDistance: "all"
    LabelingPulseAverageGradient:
      ArterialSpinLabelingType:
        ["PCASL"]
    LabelingPulseMaximumGradient:
      ArterialSpinLabelingType:
        ["PCASL"]
    LabelingPulseAverageB1:
      ArterialSpinLabelingType:
        ["PCASL"]
    LabelingPulseFlipAngle:
      ArterialSpinLabelingType:
        ["PCASL"]
    LabelingPulseInterval:
      ArterialSpinLabelingType:
        ["PCASL"]
    LabelingPulseDuration:
      ArterialSpinLabelingType:
        ["PCASL"]
    PASLType:
      ArterialSpinLabelingType:
        "PASL"
    LabelingSlabThickness:
      ArterialSpinLabelingType:
        "PASL"
    AcquisitionDuration: "all"

  consistency_schema:
    PLDType:
      type: "ConsistencyValidator"
      validation_type: "string"
      is_major: true
    ArterialSpinLabelingType:
      type: "ConsistencyValidator"
      validation_type: "string"
      is_major: true
    MRAcquisitionType:
      type: "ConsistencyValidator"
      validation_type: "string"
      is_major: true
    PulseSequenceType:
      type: "ConsistencyValidator"
      validation_type: "string"
      is_major: true
      aliases: ["ScanningSequence"]
    EchoTime:
      type: "ConsistencyValidator"
      validation_type: "floatOrArray"
      error_variation: 0.1
      warning_variation: 0.0001
      is_major: false
    RepetitionTimePreparation:
      type: "ConsistencyValidator"
      validation_type: "floatOrArray"
      error_variation: 10
      warning_variation: 0.1
      aliases: ["RepetitionTime"]
      is_major: false
    LabelingDuration:
      type: "ConsistencyValidator"
      validation_type: "floatOrArray"
      error_variation: 10
      warning_variation: 0.1
      aliases: ["NumRFBlocks"]
      is_major: false
    BackgroundSuppression:
      type: "ConsistencyValidator"
      validation_type: "boolean"
      is_major: false
    AcquisitionVoxelSize:
      type: "ConsistencyValidator"
      validation_type: "floatOrArray"
      error_variation: 0.1
      warning_variation: 0.001
      is_major: false
    FlipAngle:
      type: "ConsistencyValidator"
      validation_type: "floatOrArray"
      error_variation: 1
      warning_variation: 0.01
      is_major: false
    PostLabelingDelay:
      type: "ConsistencyValidator"
      validation_type: "floatOrArray"
      error_variation: 10
      warning_variation: 0.01
      is_major: false
    BolusCutOffFlag:
      type: "ConsistencyValidator"
      validation_type: "boolean"
      is_major: false
    BolusCutOffTechnique:
      type: "ConsistencyValidator"
      validation_type: "string"
      is_major: false
    BolusCutOffDelayTime:
      type: "ConsistencyValidator"
      validation_type: "floatOrArray"
      is_major: false
    BackgroundSuppressionNumberPulses:
      type: "ConsistencyValidator"
      validation_type: "floatOrArray"
      is_major: false
    BackgroundSuppressionPulseTime:
      type: "ConsistencyValidator"
      validation_type: "floatOrArray"
      is_major: false
    TotalAcquiredPairs:
      type: "ConsistencyValidator"
      validation_type: "floatOrArray"
      is_major: false
    AcquisitionDuration:
      type: "ConsistencyValidator"
      validation_type: "floatOrArray"
      is_major: false
    MagneticFieldStrength:
      type: "ConsistencyValidator"
      validation_type: "floatOrArray"
      is_major: false
    Manufacturer:
      type: "ConsistencyValidator"
      validation_type: "string"
      is_major: false
    M0Type:
      type: "ConsistencyValidator"
      validation_type: "string"
      is_major: false
    VascularCrushing:
      type: "ConsistencyValidator"
      validation_type: "boolean"
      is_major: false
    VascularCrushingVENC:
      type: "ConsistencyValidator"
      validation_type: "floatOrArray"
      is_major: false
    PCASLType:
      type: "ConsistencyValidator"
      validation_type: "string"
      is_major: false
    LabelingPulseAverageGradient:
      type: "ConsistencyValidator"
      validation_type: "floatOrArray"
      is_major: false
    LabelingPulseMaximumGradient:
      type: "ConsistencyValidator"
      validation_type: "floatOrArray"
      is_major: false
    LabelingPulseAverageB1:
      type: "ConsistencyValidator"
      validation_type: "floatOrArray"
      is_major: false
    LabelingPulseFlipAngle:
      type: "ConsistencyValidator"
      validation_type: "floatOrArray"
      is_major: false
    LabelingPulseInterval:
      type: "ConsistencyValidator"
      validation_type: "floatOrArray"
      is_major: false
    LabelingPulseDuration:
      type: "ConsistencyValidator"
      validation_type: "floatOrArray"
      is_major: false
    PASLType:
      type: "ConsistencyValidator"
      validation_type: "string"
      is_major: false
    LabelingSlabThickness:
      type: "ConsistencyValidator"
      validation_type: "floatOrArray"
      is_major: false